export const site = {
  name: "Teona Hotel",
  legalName: "Teona Hotel",
  url: "https://www.teonahotel.com",
  bookingUrl: "https://teona-otel.rezervasyonal.com/",
  email: "info@teonahotel.com",
  phone: {
    display: "+90 262 325 95 95",
    local: "0262 325 95 95",
    href: "tel:+902623259595",
  },
  address: {
    full: "Mehmet Ali Paşa Mah. Bağdat Cad. Erkan Sok. No:3, Bekirpaşa, İzmit / Kocaeli",
    short: "Bekirpaşa, İzmit / Kocaeli",
  },
  restaurant: {
    name: "Payidar Traditional Restaurant",
    phone: "0 530 264 89 70",
    phoneHref: "tel:+905302648970",
    instagram: "@payidarizmit",
    instagramHref: "https://www.instagram.com/payidarizmit/",
  },
  mapEmbed:
    "https://www.google.com/maps?q=Teona%20Hotel%20Izmit%20Kocaeli&output=embed",
  facts: {
    since: "2010",
    rooms: "44",
    guests: "120.000+",
    meetingCapacity: "80",
  },
  images: {
    logo: "/teona/teona-logo.png",
    logoLight: "/teona/teona-logo-light.png",
    hero: "/teona/photos/exterior-front.webp",
    exteriorFront: "/teona/photos/exterior-front.webp",
    exteriorCity: "/teona/photos/exterior-city.webp",
    exteriorAngle: "/teona/photos/exterior-angle.webp",
    corridor: "/teona/photos/corridor.webp",
    terrace: "/teona/photos/terrace.webp",
    bathroomDetail: "/teona/photos/bathroom-detail.webp",
    bathroomShower: "/teona/photos/bathroom-shower.webp",
    roomDouble: "/teona/photos/room-double.webp",
    roomTwin: "/teona/photos/room-twin.webp",
    roomMultiple: "/teona/photos/room-multiple.webp",
    economyRoom1: "/teona/photos/rooms/economy/eko-1.webp",
    economyRoom2: "/teona/photos/rooms/economy/eko-2.webp",
    economyRoom3: "/teona/photos/rooms/economy/eko-3.webp",
    economyRoom4: "/teona/photos/rooms/economy/eko-4.webp",
    frenchRoom1: "/teona/photos/rooms/french/french-1.webp",
    frenchRoom2: "/teona/photos/rooms/french/french-2.webp",
    frenchRoom3: "/teona/photos/rooms/french/french-3.webp",
    frenchRoom4: "/teona/photos/rooms/french/french-4.webp",
    frenchRoom5: "/teona/photos/rooms/french/french-5.webp",
    frenchRoom6: "/teona/photos/rooms/french/french-6.webp",
    frenchRoom7: "/teona/photos/rooms/french/french-7.webp",
    frenchRoom8: "/teona/photos/rooms/french/french-8.webp",
    suiteRoom1: "/teona/photos/rooms/suite/suite-1.webp",
    suiteRoom2: "/teona/photos/rooms/suite/suite-2.webp",
    suiteRoom3: "/teona/photos/rooms/suite/suite-3.webp",
    suiteRoom4: "/teona/photos/rooms/suite/suite-4.webp",
    suiteRoom5: "/teona/photos/rooms/suite/suite-5.webp",
    suiteRoom6: "/teona/photos/rooms/suite/suite-6.webp",
    tripleRoom1: "/teona/photos/rooms/triple/triple-1.webp",
    tripleRoom2: "/teona/photos/rooms/triple/triple-2.webp",
    tripleRoom3: "/teona/photos/rooms/triple/triple-3.webp",
    tripleRoom4: "/teona/photos/rooms/triple/triple-4.webp",
    tripleRoom5: "/teona/photos/rooms/triple/triple-5.webp",
    twinRoom1: "/teona/photos/rooms/twin/twin-1.webp",
    twinRoom2: "/teona/photos/rooms/twin/twin-2.webp",
    twinRoom3: "/teona/photos/rooms/twin/twin-3.webp",
    twinRoom4: "/teona/photos/rooms/twin/twin-4.webp",
    roomBathroom1: "/teona/photos/rooms/bathroom/bathroom-1.webp",
    roomBathroom2: "/teona/photos/rooms/bathroom/bathroom-2.webp",
    roomBathroom3: "/teona/photos/rooms/bathroom/bathroom-3.webp",
    roomBathroom4: "/teona/photos/rooms/bathroom/bathroom-4.webp",
    restaurant: "/teona/hospitality.webp",
    map: "/teona/location-map.webp",
  },
};

export const locales = ["tr", "en", "de", "ru"];

export const localeNames = {
  tr: "TR",
  en: "EN",
  de: "DE",
  ru: "RU",
};
